FROM quay.io/pypa/manylinux2014_aarch64 as build

RUN mkdir -p /io/
COPY . /io/
WORKDIR /io/

RUN python3.6 -m pip -VV
RUN python3.6 -m pip install -U pip

FROM scratch as release
COPY --from=build /io/dist /wheelhouse
