---
name: Deploy

on:
  push:
  pull_request:
    paths:
      - ".github/workflows/deploy.yml"
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build-wheels:
    name: "${{ matrix.os }}: ${{ matrix.cibw_arch }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            cibw_arch: "x86_64"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      # https://github.com/pypa/cibuildwheel
      - name: Build wheels
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1
        with:
          output-dir: dist
        # Options are supplied via environment variables:
        env:
          # Build wheels for the currently selected architecture.
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          # Include latest Python beta.
          # macOS graalpy builds fail creating a virtualenv inside cibuildwheel
          CIBW_ENABLE: 'graalpy'
          # Skip EOL Python versions
          CIBW_SKIP: "gp311* cpy*"
          # Run the test suite after each build.
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: pytest {package}/tests
          # GraalPy has a bug with progress bar rendering in pip
          PIP_PROGRESS_BAR: "off"

      - if: always()
        uses: mxschmitt/action-tmate@v3
