# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy wheels

on:
  push:
  release:
    types:
      - published
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        wheel: [aarch64]

    steps:

    - uses: actions/checkout@v2
    - run: |
       git fetch --prune --unshallow

    - uses: crazy-max/ghaction-docker-buildx@v3.3.0

    - name: Build docker image
      run: |
        docker build -t bob-the-builder --build-arg BASE=manylinux2014_aarch64 -f scripts/Dockerfile .

    - name: Build wheel
      run: |
        docker run -v "$(pwd):/io" bob-the-builder bash -c "
          rm -rf build /tmp/dist
          python setup.py -q bdist_wheel -d /tmp/dist
          auditwheel repair /tmp/dist/*.whl -w dist
        "

