name: Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: "pypy-3.11", os: windows-latest }

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          cache: pip
          cache-dependency-path: "setup.py"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U pytest
          python -m pip install .
        env:
          CFLAGS: '-DDEBUG'

      - if: always()
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - if: always()
        run: sleep 10000

      - name: Tests
        run: |
          python -m pytest --capture=no

      - name: Test without debug mode
        run: |
          git clean -Xfd
          python -m pip install --force-reinstall .
          python -m pytest

      - name: Test with coverage
        if: ${{ startsWith(matrix.os, 'ubuntu') && matrix.python-version == '3.10' }}
        run: |
          pip install -e .
          pip install coverage setuptools_scm
          CFLAGS="--coverage -O0" CXXFLAGS="--coverage -O0" python setup.py -q build_ext --inplace -f
          coverage run -m pytest
          ./scripts/coverage.sh

      - name: Upload coverage
        if: ${{ startsWith(matrix.os, 'ubuntu') && matrix.python-version == '3.10' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          plugins: pycoverage

      - name: Test with leak detection
        if: "!startsWith(matrix.python-version, 'pypy') && !startsWith(matrix.python-version, 'graalpy') && !endsWith(matrix.python-version, 't')"
        run: python -m pytest --leak-max-loops=5000 -v
